// ─── Build Orchestration Store ────────────────────────────────────────────

export type BuildStatus = "Draft Build" | "Under Technical Review" | "Approved for Deployment" | "Deployed" | "Archived";

export type BuildType =
    | "Web Application"
    | "SAP Fiori App"
    | "REST API"
    | "Automation Bot"
    | "Integration Workflow"
    | "Data Dashboard"
    | "RPA Bot";

export interface BuildCustomization {
    appName: string;
    themeColor: string;
    dbType: string;
    authType: string;
    integrations: string[];
}

export interface BuildArtifact {
    architecture: string;
    techStack: string[];
    generatedCode: string;
    apiStructure: string;
    testPlan: string;
    deploymentRecommendation: string;
    botLogic?: string;
}

export interface BuildRecord {
    id: string;
    brdId: string;
    brdTitle: string;
    buildType: BuildType;
    version: string;
    status: BuildStatus;
    createdAt: string;
    updatedAt: string;
    customization: BuildCustomization;
    artifact: BuildArtifact;
    logs: string[];
}

// ─── Orchestration Steps ─────────────────────────────────────────────────

export interface OrchestrationStep {
    id: string;
    label: string;
    agent: string;
    agentColor: string;
    description: string;
    duration: number; // ms
}

export const ORCHESTRATION_STEPS: OrchestrationStep[] = [
    { id: "brd-pull", label: "Pull Approved BRD", agent: "BRD Generator", agentColor: "bg-purple-500", description: "Loading BRD sections and requirements...", duration: 1200 },
    { id: "architect", label: "Solution Architecture", agent: "Solution Architect", agentColor: "bg-[#00338D]", description: "Designing technical architecture blueprint...", duration: 2400 },
    { id: "tech-arch", label: "Generate Architecture Doc", agent: "Solution Architect", agentColor: "bg-[#00338D]", description: "Documenting system design decisions...", duration: 1600 },
    { id: "code-build", label: "Generate Code / Bot", agent: "Code Builder", agentColor: "bg-emerald-600", description: "Writing implementation code and logic...", duration: 3200 },
    { id: "code-review", label: "Code Quality Review", agent: "Code Builder", agentColor: "bg-emerald-600", description: "Running lint checks and optimisations...", duration: 1400 },
    { id: "test-plan", label: "Generate Test Plan", agent: "Test Orchestrator", agentColor: "bg-amber-500", description: "Creating unit, integration, and UAT test cases...", duration: 1800 },
    { id: "deploy-rec", label: "Deployment Recommendation", agent: "Solution Architect", agentColor: "bg-[#00338D]", description: "Finalising deployment strategy and infrastructure plan...", duration: 1000 },
];

// ─── Build Output Generator ───────────────────────────────────────────────

export function generateArtifact(buildType: BuildType, brdTitle: string, customization: BuildCustomization): BuildArtifact {
    const appName = customization.appName || brdTitle.split(" ").slice(0, 3).join(" ");

    const codeMap: Record<BuildType, string> = {
        "Web Application": `// ${appName} – React + Next.js Application
// Generated by Code Builder Agent

import { useState, useEffect } from 'react';

interface DashboardProps {
  userId: string;
  projectId: string;
}

export default function ${appName.replace(/\s/g, "")}Dashboard({ userId, projectId }: DashboardProps) {
  const [data, setData] = useState<Record<string, unknown>[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchProjectData(projectId).then(res => {
      setData(res);
      setLoading(false);
    });
  }, [projectId]);

  return (
    <main className="p-8">
      <h1 className="text-2xl font-bold mb-6">{appName}</h1>
      {loading ? <Spinner /> : <DataGrid rows={data} />}
    </main>
  );
}`,

        "SAP Fiori App": `// ${appName} – SAP Fiori Elements App
// Generated by Code Builder Agent (SAPUI5 / OData v4)

sap.ui.require([
  "sap/ui/core/UIComponent",
  "sap/ui/model/odata/v4/ODataModel"
], function(UIComponent, ODataModel) {
  "use strict";

  return UIComponent.extend("com.kpmg.${appName.replace(/\s/g, "").toLowerCase()}.Component", {
    metadata: { manifest: "json" },

    init: function() {
      UIComponent.prototype.init.apply(this, arguments);
      const oModel = new ODataModel({
        serviceUrl: "/sap/opu/odata4/sap/api_${appName.replace(/\s/g, "_").toLowerCase()}/",
        synchronizationMode: "None",
        operationMode: "Server"
      });
      this.setModel(oModel);
      this.getRouter().initialize();
    }
  });
});`,

        "REST API": `// ${appName} – REST API
// Generated by Code Builder Agent (Node.js + Express)

import express, { Request, Response } from 'express';
import { validateJWT, auditLog } from './middleware';

const router = express.Router();

// GET /api/v1/${appName.replace(/\s/g, "-").toLowerCase()}
router.get('/', validateJWT, auditLog, async (req: Request, res: Response) => {
  const { projectId, page = 1, limit = 50 } = req.query;
  const data = await db.query(
    'SELECT * FROM records WHERE project_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3',
    [projectId, limit, (Number(page) - 1) * Number(limit)]
  );
  res.json({ success: true, data: data.rows, total: data.rowCount });
});

// POST /api/v1/${appName.replace(/\s/g, "-").toLowerCase()}
router.post('/', validateJWT, auditLog, async (req: Request, res: Response) => {
  const validated = await schema.validate(req.body);
  const result = await db.query(
    'INSERT INTO records (project_id, payload, created_by) VALUES ($1, $2, $3) RETURNING *',
    [validated.projectId, validated.data, req.user.id]
  );
  res.status(201).json({ success: true, record: result.rows[0] });
});

export default router;`,

        "Automation Bot": `// ${appName} – Automation Bot
// Generated by Code Builder Agent (Python + RPA Framework)

from rpa_framework import Browser, SAP, Logger

class ${appName.replace(/\s/g, "")}Bot:
    def __init__(self, config: dict):
        self.browser = Browser(headless=True)
        self.sap = SAP(server=config['SAP_SERVER'])
        self.logger = Logger(name='${appName}Bot')

    def run(self, payload: dict) -> dict:
        """Main bot execution flow"""
        try:
            self.logger.info(f"Starting ${appName} Bot run ID: {payload['run_id']}")
            
            # Step 1: Login to SAP
            session = self.sap.login(
                client=payload['client'],
                user=payload['service_user'],
                password=payload['service_password']
            )
            
            # Step 2: Navigate to transaction
            session.start_transaction('ME21N')  # Create Purchase Order
            
            # Step 3: Fill form fields
            session.fill_field('wnd[0]/usr/subSCREEN_4400', payload['vendor'])
            session.fill_field('wnd[0]/usr/txtEKKO-EKGRP', payload['purch_group'])
            
            # Step 4: Submit and capture result
            result = session.press_button('wnd[0]/tbar[0]/btn[11]')
            self.logger.success(f"PO Created: {result['doc_number']}")
            return {"status": "success", "document": result['doc_number']}

        except Exception as e:
            self.logger.error(f"Bot failed: {str(e)}")
            return {"status": "error", "message": str(e)}`,

        "Integration Workflow": `// ${appName} – Integration Workflow
// Generated by Code Builder Agent (SAP CPI / iFlow)

<IntegrationFlow Name="${appName.replace(/\s/g, "_")}">
  <Description>Auto-generated iFlow for ${brdTitle}</Description>
  <Sender>
    <Adapter type="HTTPS">
      <BasePath>/${appName.replace(/\s/g, "-").toLowerCase()}</BasePath>
      <Authentication>ClientCertificate</Authentication>
    </Adapter>
  </Sender>
  <ProcessSteps>
    <ContentModifier name="SetHeaders">
      <MessageHeader><Name>X-Correlation-ID</Name><Value>\${property.correlationId}</Value></MessageHeader>
    </ContentModifier>
    <Mapping name="TransformPayload">
      <SourceMessage>InboundFormat</SourceMessage>
      <TargetMessage>SAPIDoCFormat</TargetMessage>
    </Mapping>
    <RequestReply name="CallSAPBackend">
      <Receiver><Name>SAP_ERP</Name></Receiver>
      <Channel><Adapter type="RFC"/></Channel>
    </RequestReply>
    <ExceptionSubprocess>
      <ErrorHandling>
        <AlertEmail>sap-ops@kpmg.com</AlertEmail>
        <RetryCount>3</RetryCount>
      </ErrorHandling>
    </ExceptionSubprocess>
  </ProcessSteps>
</IntegrationFlow>`,

        "Data Dashboard": `// ${appName} – Analytics Dashboard
// Generated by Code Builder Agent (SAP Analytics Cloud / React)

import { BarChart, LineChart, KPICard } from '@sap/analytical-card';
import { ODataProvider } from '@sap/ui5-react';

const ${appName.replace(/\s/g, "")}Dashboard = () => {
  const kpis = [
    { title: 'Total Processed', value: '4,821', trend: '+12%', color: 'positive' },
    { title: 'Avg. Cycle Time', value: '2.4h', trend: '-8%', color: 'positive' },
    { title: 'Error Rate', value: '0.3%', trend: '-2%', color: 'positive' },
    { title: 'Open Items', value: '47', trend: '+5', color: 'critical' },
  ];

  return (
    <ODataProvider serviceUrl="/sap/opu/odata/analytics/">
      <div className="dashboard-grid">
        {kpis.map(kpi => <KPICard key={kpi.title} {...kpi} />)}
        <BarChart title="Monthly Volume" dimension="Month" measures={['Volume', 'Target']} />
        <LineChart title="Cycle Time Trend" dimension="Week" measures={['AvgTime', 'Benchmark']} />
      </div>
    </ODataProvider>
  );
};`,

        "RPA Bot": `# ${appName} – RPA Bot
# Generated by Code Builder Agent (UiPath / Python RPA)

from uipath_orchestrator import OrchestratorClient, Job
from sap_gui_scripting import SAPSession

def ${appName.replace(/\s/g, "_").toLowerCase()}_bot(config: dict):
    """
    RPA Bot: ${brdTitle}
    Trigger: Scheduled / Event-driven
    Target: SAP GUI + Document Portal
    """
    orch = OrchestratorClient(
        url=config['ORCHESTRATOR_URL'],
        tenant=config['TENANT'],
        client_id=config['CLIENT_ID']
    )
    
    job = Job(
        process_name='${appName.replace(/\s/g, "_")}',
        robot_name='ROBOT_SAP_01',
        input_args={
            'environment': config['ENVIRONMENT'],
            'batch_date': config['PROCESSING_DATE'],
            'notify_on_error': 'sap-ops@kpmg.com'
        }
    )
    
    result = orch.start_job(job)
    print(f"Job started: {result.job_key} | Status: {result.state}")
    return result`,
    };

    const archMap: Record<BuildType, string> = {
        "Web Application": `**Frontend:** React 18 + Next.js 14 (App Router) + TypeScript\n**State:** Zustand + React Query\n**Styling:** Tailwind CSS + shadcn/ui\n**Auth:** OAuth 2.0 (Azure AD) + JWT\n**API Layer:** REST (Node.js/Express) + tRPC\n**DB:** ${customization.dbType || "PostgreSQL"} + Prisma ORM\n**Hosting:** Azure App Service + Azure CDN\n**CI/CD:** GitHub Actions → Azure DevOps`,
        "SAP Fiori App": `**UI Framework:** SAPUI5 5.x / Fiori Elements\n**OData:** v4 with batch requests\n**Backend:** SAP BTP ABAP Environment\n**Auth:** SAP IdP + OAuth 2.0 SAML Bearer\n**Transport:** SAP CTS+ (DEV→QAS→PRD)\n**DB:** SAP HANA Cloud\n**CI/CD:** SAP Cloud Transport Management`,
        "REST API": `**Runtime:** Node.js 20 LTS + TypeScript\n**Framework:** Express.js + OpenAPI 3.1\n**Auth:** JWT + API Key (dual mode)\n**DB:** ${customization.dbType || "PostgreSQL"} + Redis Cache\n**Docs:** Swagger UI (auto-generated)\n**Rate Limiting:** 1000 req/min per tenant\n**Monitoring:** Datadog APM\n**Deploy:** Docker → Azure Container Apps`,
        "Automation Bot": `**Framework:** Python RPA Framework + SAP GUI Scripting\n**Orchestration:** SAP Intelligent RPA\n**Scheduling:** Azure Logic Apps (CRON)\n**Logging:** Azure Monitor + Log Analytics\n**Error Handling:** Retry (3x) + Email Alert\n**Security:** Service Account + Vault Secrets\n**Deploy:** Azure DevOps Pipeline`,
        "Integration Workflow": `**Platform:** SAP Cloud Platform Integration (CPI)\n**Pattern:** Request-Reply + Async Polling\n**Protocol:** HTTPS inbound / RFC outbound\n**Mapping:** XSLT + Groovy Script\n**Error Handling:** Dead Letter Queue + Alert\n**Monitoring:** SAP Integration Suite Operations\n**Transport:** CPI Git-based deployment`,
        "Data Dashboard": `**Analytics Platform:** SAP Analytics Cloud (SAC)\n**Data Source:** SAP HANA Live Connection\n**Refresh:** Real-time (15 min delta)\n**Auth:** SAP SSO + SAML 2.0\n**Embedding:** SAC Embed API v2\n**Export:** PDF, Excel, CSV\n**Mobile:** SAC Mobile App compatible`,
        "RPA Bot": `**Platform:** UiPath Enterprise RPA + Orchestrator\n**Target:** SAP GUI + Document Portal\n**Trigger:** Schedule (daily 02:00) + Event\n**Runtime:** Unattended Robot × 3\n**Queue:** UiPath Queues with retry logic\n**Logging:** UiPath Insights + Kibana\n**Deploy:** UiPath CI/CD Pipeline`,
    };

    return {
        architecture: archMap[buildType],
        techStack: archMap[buildType].split("\n").map(l => l.replace(/^\*\*[^:]+:\*\* /, "")).filter(Boolean),
        generatedCode: codeMap[buildType],
        apiStructure: buildType === "REST API"
            ? `GET    /api/v1/${appName.replace(/\s/g, "-").toLowerCase()}          → List records\nGET    /api/v1/${appName.replace(/\s/g, "-").toLowerCase()}/:id       → Get single record\nPOST   /api/v1/${appName.replace(/\s/g, "-").toLowerCase()}          → Create record\nPUT    /api/v1/${appName.replace(/\s/g, "-").toLowerCase()}/:id       → Update record\nDELETE /api/v1/${appName.replace(/\s/g, "-").toLowerCase()}/:id       → Archive record\nGET    /api/v1/${appName.replace(/\s/g, "-").toLowerCase()}/export    → Export data`
            : `Endpoint: /${appName.replace(/\s/g, "-").toLowerCase()}\nIntegration: SAP OData v4 / RFC\nAuth: OAuth 2.0 Bearer Token`,
        testPlan: `**GENERATED TEST PLAN — ${appName}**\n\n**Unit Tests (12 cases):**\nUT-001: Validate input schema for all required fields\nUT-002: Test error handling for missing mandatory parameters\nUT-003: Verify authentication token validation logic\nUT-004: Test pagination with boundary values (0, 1, max)\n\n**Integration Tests (8 cases):**\nIT-001: End-to-end flow — create → process → output\nIT-002: SAP backend roundtrip with mock data\nIT-003: Error propagation from backend to UI\nIT-004: Concurrent user simulation (50 users)\n\n**UAT Scenarios (5):**\nUAT-001: Business user completes primary workflow without assistance\nUAT-002: Error state recovery without data loss\nUAT-003: Mobile device compatibility check (iOS + Android)\nUAT-004: Performance under peak load (200 concurrent)\nUAT-005: Security: attempt unauthorised access — verify 403`,
        deploymentRecommendation: `**DEPLOYMENT STRATEGY: Blue-Green**\n\n**Environments:**\n└── DEV → Build + Unit Test\n└── QAS → Integration + UAT\n└── PRD → Production (Blue-Green)\n\n**Pre-Deployment Checklist:**\n☐ Security review sign-off (no High/Critical open)\n☐ Performance test passed (< 2s p95)\n☐ Stakeholder UAT sign-off\n☐ Rollback plan reviewed by IT\n\n**Go-Live Window:** Off-peak (Sat 23:00–02:00 AEST)\n**Rollback Trigger:** Error rate > 1% in 5-min window`,
        botLogic: buildType === "Automation Bot" || buildType === "RPA Bot"
            ? `TRIGGER → VALIDATE INPUT → LOGIN SAP → NAVIGATE TRANSACTION → FILL FIELDS → SUBMIT → CAPTURE RESULT → LOG → NOTIFY → END`
            : undefined,
    };
}

// ─── Build AI Responses ───────────────────────────────────────────────────

export const BUILD_AI_RESPONSES: Record<string, string[]> = {
    "explain-architecture": [
        "🏗️ Explaining architecture in plain language...\n\n",
        "**In Simple Terms:**\n\n",
        "Think of the architecture like a modern office building:\n\n",
        "• **Frontend** = The reception desk — what users see and interact with\n",
        "• **API Layer** = Phone lines — carries information between departments\n",
        "• **Backend** = The processing department — handles all the business logic\n",
        "• **Database** = The filing room — stores all your data safely\n",
        "• **Auth System** = Security guard — checks who is allowed in\n\n",
        "The SAP integration connects your new system directly to your SAP processes, so data flows automatically without manual steps.\n\n",
        "✅ **Architecture uses industry-standard patterns tested on 500+ enterprise projects.**",
    ],
    "suggest-improvements": [
        "💡 Analysing build configuration for improvements...\n\n",
        "**Recommendations:**\n\n",
        "1. **Add Redis Caching** → Reduce database load by 60% for read-heavy operations\n",
        "2. **Implement Rate Limiting** → Protect API from abuse (suggested: 1,000 req/min/tenant)\n",
        "3. **Add Health Check Endpoint** → Enable load balancer and monitoring integration\n",
        "4. **Enable Audit Logging** → Log all write operations for compliance (GDPR/SOX)\n",
        "5. **Add API Versioning** → Use `/api/v1/` prefix to allow non-breaking future upgrades\n\n",
        "✅ **5 improvements identified. Applying any will trigger a delta regeneration.**",
    ],
    "estimate-effort": [
        "⏱️ Calculating development effort estimate...\n\n",
        "**Effort Breakdown:**\n\n",
        "| Phase | Duration | Team |\n",
        "|---|---|---|\n",
        "| Setup & Config | 2 days | 1 Dev |\n",
        "| Core Development | 8 days | 2 Devs |\n",
        "| Integration Testing | 3 days | 1 Dev + 1 QA |\n",
        "| UAT Support | 2 days | 1 Dev |\n",
        "| Deployment | 1 day | 1 DevOps |\n\n",
        "**Total: ~16 working days (3.2 weeks)**\n",
        "**Estimated Cost: $28,000–$42,000 (based on KPMG rates)**\n\n",
        "✅ **Estimate assumes AI-generated code reduces effort by ~40% vs manual build.**",
    ],
    "predict-risks": [
        "⚠️ Scanning generated solution for risks...\n\n",
        "**Identified Risks:**\n\n",
        "🔴 R-001 (HIGH): SAP RFC connection requires BASIS team setup — typically 3 day lead time.\n",
        "🟠 R-002 (MEDIUM): OAuth 2.0 Azure AD setup needs IT Security approval (2-week SLA).\n",
        "🟠 R-003 (MEDIUM): Data migration from legacy system not included in this build.\n",
        "🟡 R-004 (LOW): CORS configuration required if frontend hosted on separate domain.\n\n",
        "**Mitigations:**\n",
        "→ R-001: Raise BASIS request immediately to avoid delay.\n",
        "→ R-002: Submit Azure AD app registration request via IT portal today.\n\n",
        "✅ **4 risks identified. None are blockers if actioned within 1 week.**",
    ],
    "cost-estimate": [
        "💰 Generating cost and time estimate...\n\n",
        "**Build Cost Estimate:**\n\n",
        "| Item | Cost |\n",
        "|---|---|\n",
        "| AI-Generated Code (this build) | $0 (included) |\n",
        "| Developer review & validation | $8,000–$12,000 |\n",
        "| Infrastructure (Azure, 12 months) | $6,000–$9,000/yr |\n",
        "| SAP licences (if additional named users) | $3,000–$8,000/yr |\n",
        "| Testing & UAT support | $4,000–$6,000 |\n\n",
        "**Total Year 1: $21,000–$35,000**\n",
        "**Ongoing/yr: $9,000–$17,000**\n\n",
        "✅ **Compared to traditional development: 60–70% cost reduction using AI build.**",
    ],
};
