"use client";

import { useState } from "react";
import { Search, Download, CheckCircle2, Star, Package2 } from "lucide-react";

interface Extension {
    id: string;
    name: string;
    publisher: string;
    description: string;
    stars: number;
    installs: string;
    category: string;
    installed: boolean;
    icon: string;
    iconColor: string;
}

const EXTENSIONS: Extension[] = [
    { id: "jira",       name: "Jira Integration",        publisher: "Atlassian",    description: "Export BRD requirements as Jira epics and stories automatically.",         stars: 4.8, installs: "2.1M", category: "Integration", installed: false, icon: "J",  iconColor: "#0052CC" },
    { id: "confluence", name: "Confluence Publisher",    publisher: "Atlassian",    description: "Publish approved BRDs directly to Confluence as formatted pages.",          stars: 4.6, installs: "1.8M", category: "Integration", installed: false, icon: "C",  iconColor: "#172B4D" },
    { id: "github",     name: "GitHub Copilot",          publisher: "GitHub",       description: "AI-assisted code suggestions inside the developer workspace.",               stars: 4.9, installs: "5.4M", category: "AI",          installed: true,  icon: "G",  iconColor: "#24292F" },
    { id: "slack",      name: "Slack Notifications",     publisher: "Slack",        description: "Send BRD status updates and agent completions to Slack channels.",          stars: 4.5, installs: "3.2M", category: "Integration", installed: false, icon: "S",  iconColor: "#4A154B" },
    { id: "teams",      name: "Microsoft Teams",         publisher: "Microsoft",    description: "Notify Teams channels on BRD approvals, reviews and deployments.",          stars: 4.3, installs: "2.7M", category: "Integration", installed: false, icon: "T",  iconColor: "#6264A7" },
    { id: "figma",      name: "Figma Design Sync",       publisher: "Figma",        description: "Import Figma components and design tokens into the UI/UX agent context.",   stars: 4.7, installs: "980K", category: "Design",      installed: false, icon: "F",  iconColor: "#F24E1E" },
    { id: "docker",     name: "Docker Build",            publisher: "Docker",       description: "Build and push Docker images directly from the deployment agent output.",   stars: 4.6, installs: "1.5M", category: "DevOps",      installed: true,  icon: "D",  iconColor: "#2496ED" },
    { id: "sonar",      name: "SonarQube",               publisher: "SonarSource", description: "Run static code analysis on generated code before acceptance.",              stars: 4.4, installs: "1.1M", category: "Quality",     installed: false, icon: "SQ", iconColor: "#CB2027" },
    { id: "terraform",  name: "Terraform Cloud",         publisher: "HashiCorp",    description: "Apply Terraform plans generated by the deployment agent to your infra.",    stars: 4.5, installs: "760K", category: "DevOps",      installed: false, icon: "TF", iconColor: "#7B42BC" },
    { id: "openai",     name: "GPT-4o Turbo",            publisher: "OpenAI",       description: "Upgrade agents to use GPT-4o Turbo for faster, cheaper completions.",       stars: 4.9, installs: "4.8M", category: "AI",          installed: true,  icon: "AI", iconColor: "#10A37F" },
    { id: "claude",     name: "Claude 3.5 Sonnet",       publisher: "Anthropic",    description: "Use Claude 3.5 Sonnet as an alternative model across all pipeline agents.", stars: 4.8, installs: "2.3M", category: "AI",          installed: false, icon: "CL", iconColor: "#D97757" },
    { id: "sharepoint", name: "SharePoint Storage",      publisher: "Microsoft",    description: "Store and retrieve BRD documents directly from SharePoint document libs.",  stars: 4.2, installs: "890K", category: "Storage",     installed: false, icon: "SP", iconColor: "#0078D4" },
];

const CATEGORIES = ["All", "AI", "Integration", "DevOps", "Design", "Quality", "Storage"];

interface Props { dark: boolean; }

export default function ExtensionsPanel({ dark }: Props) {
    const [search, setSearch] = useState("");
    const [category, setCategory] = useState("All");
    const [installed, setInstalled] = useState<Record<string, boolean>>(
        Object.fromEntries(EXTENSIONS.map(e => [e.id, e.installed]))
    );

    const bg       = dark ? "#252526" : "#f3f3f3";
    const headerBg = dark ? "#2c2c2c" : "#e8e8e8";
    const cardBg   = dark ? "#2a2a2a" : "#ffffff";
    const text      = dark ? "#cccccc" : "#1e1e1e";
    const muted     = dark ? "#777777" : "#6b7280";
    const border    = dark ? "rgba(255,255,255,0.07)" : "rgba(0,0,0,0.09)";
    const inputBg   = dark ? "rgba(255,255,255,0.07)" : "rgba(0,0,0,0.05)";
    const hoverBg   = dark ? "rgba(255,255,255,0.05)" : "rgba(0,0,0,0.03)";

    const filtered = EXTENSIONS.filter(e => {
        const matchSearch = e.name.toLowerCase().includes(search.toLowerCase()) ||
                            e.publisher.toLowerCase().includes(search.toLowerCase()) ||
                            e.description.toLowerCase().includes(search.toLowerCase());
        const matchCat = category === "All" || e.category === category;
        return matchSearch && matchCat;
    });

    const installedCount = Object.values(installed).filter(Boolean).length;

    const toggle = (id: string) => setInstalled(prev => ({ ...prev, [id]: !prev[id] }));

    return (
        <div className="flex-1 flex flex-col overflow-hidden" style={{ background: bg }}>

            {/* Header */}
            <div className="shrink-0 px-4 py-3" style={{ background: headerBg, borderBottom: `1px solid ${border}` }}>
                <div className="flex items-center gap-2 mb-3">
                    <Package2 size={14} style={{ color: muted }} />
                    <span className="text-[12px] font-semibold" style={{ color: text }}>Extensions</span>
                    <span className="ml-auto text-[10px] px-1.5 py-0.5 rounded font-mono"
                        style={{ background: "rgba(0,51,141,0.12)", color: "#3b82f6" }}>
                        {installedCount} installed
                    </span>
                </div>

                {/* Search */}
                <div className="relative">
                    <Search size={11} className="absolute left-2.5 top-1/2 -translate-y-1/2" style={{ color: muted }} />
                    <input
                        value={search}
                        onChange={e => setSearch(e.target.value)}
                        placeholder="Search extensions…"
                        className="w-full pl-7 pr-3 py-1.5 rounded-lg text-[11px] focus:outline-none"
                        style={{ background: inputBg, border: `1px solid ${border}`, color: text }}
                    />
                </div>

                {/* Category filters */}
                <div className="flex gap-1 mt-2 flex-wrap">
                    {CATEGORIES.map(c => (
                        <button key={c} onClick={() => setCategory(c)}
                            className="px-2 py-0.5 rounded text-[10px] font-medium transition-all"
                            style={{
                                background: category === c ? "#00338D" : inputBg,
                                color: category === c ? "#ffffff" : muted,
                                border: `1px solid ${category === c ? "#00338D" : border}`,
                            }}>
                            {c}
                        </button>
                    ))}
                </div>
            </div>

            {/* Extension list */}
            <div className="flex-1 overflow-y-auto px-3 py-2 space-y-1.5">
                {filtered.map(ext => {
                    const isOn = installed[ext.id];
                    return (
                        <div key={ext.id}
                            className="flex items-start gap-3 p-3 rounded-xl transition-colors"
                            style={{ background: cardBg, border: `1px solid ${border}` }}
                            onMouseEnter={e => (e.currentTarget.style.background = dark ? "#323232" : "#f9f9f9")}
                            onMouseLeave={e => (e.currentTarget.style.background = cardBg)}>

                            {/* Icon */}
                            <div className="w-9 h-9 rounded-lg shrink-0 flex items-center justify-center text-[10px] font-black text-white"
                                style={{ background: ext.iconColor }}>
                                {ext.icon}
                            </div>

                            {/* Info */}
                            <div className="flex-1 min-w-0">
                                <div className="flex items-center gap-2">
                                    <span className="text-[12px] font-semibold truncate" style={{ color: text }}>{ext.name}</span>
                                    {isOn && <CheckCircle2 size={10} className="text-emerald-400 shrink-0" />}
                                </div>
                                <p className="text-[10px] truncate" style={{ color: muted }}>{ext.publisher}</p>
                                <p className="text-[10px] mt-0.5 leading-relaxed line-clamp-2" style={{ color: muted }}>{ext.description}</p>
                                <div className="flex items-center gap-2 mt-1">
                                    <span className="text-[9px] flex items-center gap-0.5" style={{ color: muted }}>
                                        <Star size={8} className="fill-current text-amber-400" /> {ext.stars}
                                    </span>
                                    <span className="text-[9px]" style={{ color: muted }}>{ext.installs}</span>
                                    <span className="text-[9px] px-1 rounded" style={{ background: inputBg, color: muted }}>{ext.category}</span>
                                </div>
                            </div>

                            {/* Install / Uninstall */}
                            <button onClick={() => toggle(ext.id)}
                                className="shrink-0 px-2.5 py-1 rounded-lg text-[10px] font-semibold transition-all"
                                style={isOn
                                    ? { background: "rgba(52,211,153,0.10)", color: "#34d399", border: "1px solid rgba(52,211,153,0.25)" }
                                    : { background: "rgba(0,51,141,0.10)", color: "#3b82f6", border: "1px solid rgba(59,130,246,0.25)" }}>
                                {isOn ? "Installed" : <span className="flex items-center gap-1"><Download size={9} /> Install</span>}
                            </button>
                        </div>
                    );
                })}
            </div>
        </div>
    );
}
